[build]
command = "hugo --gc --minify"
publish = "public"

[context.production.environment]
HUGO_ENABLEGITINFO = "true"
HUGO_ENV = "production"
HUGO_VERSION = "0.111.3"

[context.deploy-preview.environment]
HUGO_VERSION = "0.111.3"
