backend:
  name: github
  repo: bouncmpe/website
  branch: main

# backend:
#   name: git-gateway
# local_backend: true

logo_url: /images/logo.png

media_folder: assets/images/uploads
public_folder: /images/uploads
search: false

slug:
  encoding: "ascii"
  clean_accents: true

i18n:
  structure: multiple_files
  locales: [en, tr]
  default_locale: en

collections:
  - name: "news"
    label: "Latest News"
    folder: "content/news"
    slug: "{{date | date('YYYY-MM-DD')}}-news-{{title | lower}}"
    path: "{{slug}}/index"
    media_folder: ""
    public_folder: ""
    create: true
    i18n: true
    editor:
      preview: false
    filter: { field: "type", value: "news" }
    fields:
      - {
          label: "Type",
          name: "type",
          widget: "hidden",
          default: "news",
          i18n: "duplicate",
        }
      - { label: "Title", name: "title", widget: "string", i18n: true }
      - {
          label: "Description",
          name: "description",
          widget: "string",
          i18n: true,
          required: false,
        }
      - {
          label: "Publish Date",
          name: "date",
          widget: "datetime",
          date_format: "DD MMMM YYYY",
          time_format: false,
          format: "YYYY-MM-DD",
          i18n: "duplicate",
        }
      - {
          label: "Image",
          name: "image",
          widget: "image",
          allow_multiple: false,
          i18n: "duplicate",
          required: false,
        }
      - {
          label: "Image Caption",
          name: "image_caption",
          widget: "string",
          i18n: true,
          required: false,
        }
      - {
          label: "Body",
          name: "body",
          widget: "markdown",
          default: "",
          i18n: true,
        }

  - name: "event"
    label: "Events"
    label_singular: "Event"
    folder: "content/events"
    slug: "{{expiryDate | date('YYYY-MM-DD')}}-{{type}}-{{speaker | lower}}"
    path: "{{slug}}/index"
    media_folder: ""
    public_folder: ""
    create: true
    i18n: true
    editor:
      preview: false
    preview_path_date_field: "expiryDate"
    sortable_fields: ["expiryDate", "speaker"]
    view_filters:
      - label: PhD
        field: type
        pattern: phd-thesis-defense
      - label: MS
        field: type
        pattern: ms-thesis-defense
      - label: Seminar
        field: type
        pattern: seminar
    fields:
      - {
          label: "Type",
          name: "type",
          widget: "select",
          options:
            [
              { label: "MS Thesis Defense", value: "ms-thesis-defense" },
              { label: "PhD Thesis Defense", value: "phd-thesis-defense" },
              { label: "Seminar", value: "seminar" },
            ],
          default: "ms-thesis-defense",
          i18n: "duplicate",
        }
      - { label: "Title", name: "title", widget: "string", i18n: true }
      - {
          label: "Speaker",
          name: "speaker",
          widget: "string",
          i18n: "duplicate",
        }
      - {
          label: "Event Date",
          name: "expiryDate",
          widget: "datetime",
          date_format: "DD MMMM YYYY",
          time_format: false,
          format: "YYYY-MM-DD",
          i18n: "duplicate",
        }
      - {
          label: "Start Time",
          name: "startTime",
          widget: "datetime",
          date_format: false,
          time_format: "h:mm A",
          format: "HH:mm",
          i18n: "duplicate",
        }
      - {
          label: "Finish Time",
          name: "finishTime",
          widget: "datetime",
          date_format: false,
          time_format: "h:mm A",
          format: "HH:mm",
          i18n: "duplicate",
        }
      - {
          label: "Location",
          name: "location",
          widget: "string",
          i18n: "duplicate",
        }
      - {
          label: "Meeting Link",
          name: "meeting-link",
          widget: "string",
          i18n: "duplicate",
          required: false,
        }
      - {
          label: "Description",
          name: "body",
          widget: "markdown",
          default: "",
          i18n: true,
        }
